#import "templates/nwp-syllabus.typ": template, grade-table
#import "lib/timetable.typ": *
#import "params.typ": *
#import "@preview/abbr:0.3.0"

#abbr.make(
  ("CCMEA", "Cultural Contact and the Making of European Art since the Age of Exploration"),
)

#show: doc => template(
  number: [AR1205],
  name: [Introduction to the History of Global Art II],
  instructor: "Kaveh Rafie",
  email: "krafie@nwpolytech.ca",
  semester: "Fall",
  year: 2026,
  dept: "Fine Arts",
  logo: "../../../assets/logo.svg",
  officeHours: [Wednesdays 2:30 PM -- 3:30 PM or by appointment],
  officeLoc: link("https://nwpolytech.zoom.us/xxxx"),
  doc,
)


= Calendar Description

The course examines art from the 15th century to the 20th century, focusing on various art forms with examples from both the non-Western and Western canons. It includes case studies from diverse regions, which explore a range of different forms of expression. This course will familiarize students with basic terms and concepts used in discussing art and cultural artifacts. While it is structured chronologically, it does not cover every period or geographical region. The purpose of the course is to equip students with the knowledge and skills necessary for further education by providing them with a foundational understanding of art history and some of its most significant moments.

= Prerequisite(s)/Corequisite(s)
None

= Required Materials
No textbook requires. Readings will be provided on #underline[Perusall]. 

= Delivery Mode

This course is delivered synchronously online via Zoom: #link("https://nwpolytech.zoom.us/xxxx")

= LEARNING OUTCOMES

By the end of this course, students will be able to:

- Identify and describe major art movements and styles from the 15th to present.
- Analyze and interpret artworks using appropriate art historical terminology.
- Understand the cultural and historical contexts of various art forms.
- Critically engage with visual materials and articulate informed perspectives on art.
- Conduct basic research in art history and present findings effectively.

= Transferability 

Please consult the Alberta Transfer Guide for more information. You may check the transferability of this course at the Alberta Transfer Guide main page http://www.transferalberta.alberta.ca.

⚠️ For courses with alpha (letter) grading, a grade of D or D+ may not be acceptable for transfer to other post-secondary institutions. *Students are cautioned that it is their responsibility to contact the receiving institutions to ensure transferability.*

= Evaluations


Please note that most universities will not accept your course for transfer credit *IF* your grade is *less than C-*.

= Grading Chart for courses with Alpha Grading

#grade-table

⚠️ #underline[Grades for this course will be assigned as a percentage.]

#pagebreak()

= Course Schedule (Tentative)\* 

#schedule(
  start: start-date,
  days: class-days,
  holidays: holidays,
  events: (
    session-intro,
    session-southern-northern-renaissance,
    session-high-renaissance,
    session-mannerism,
    session-new-world,
    session-mongol,
    session-chinese-art,
    session-japanese-art,
    session-south-asian-art,
    session-african-art,
    session-pacific-art,
    session-aztec-inca,
    session-north-american-indigenous,
    session-baroque-in-southern-europe,
    session-baroque-in-northern-europe,
    session-rococo,
    session-neoclassicism-romanticism,
    session-realism,
    session-impressionism,
    session-post-impressionism,
    session-pre-war,
    session-interwar,
    session-post-war,
    session-neo-avant-garde,
    session-final
  ),
)

// Jan 6 2026 - Apr 23 2026
// last day of classes: Apr 13 2026

#pagebreak()

= Student Responsibilities

On-line Communication &amp; Professionalism: Students are expected to maintain a
high-level of professionalism across all course-related communications. Please
conduct your communications as you would any other professional experience.
Treat your colleagues with respect!
• Join the lecture to on time and remain for duration of class and related activities.
• Students can expect to put in a minimum of 4 hours per week on out-of-
class work. Assignments will be expected on the date required.

= Statement on Academic Misconduct

Academic Misconduct will not be tolerated. For a more precise definition of academic misconduct and its consequences, refer to the Student Rights and Responsibilities policy available https://www.nwpolytech.ca/about/polytechnic-leadership/policies-directory.

\*\*Note: all Academic and Administrative policies are available on the same page.

= Additional Information:

== Plagarism and the Use of LLMs or AI Tools
Plagiarism is the presentation of the work, ideas, or data of another person as one’s own. This includes work obtained through the use of LLMs (Large Language Models) or other AI tools. Students must properly cite any sources used in their assignments, including any content generated by AI tools. Failure to do so may result in academic penalties as outlined in the institution's academic integrity policies.


